language: minimal

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "eu-west-2"
  app: "jeerer"
  env: "jeerer-env"
  bucket_name: "elasticbeanstalk-eu-west-2-255446756174"
  edge: true
  on:
    branch: master
