# Generated by Django 2.2.7 on 2019-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeerer_app', '0002_cardmodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
