# Generated by Django 2.2.7 on 2019-11-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeerer_app', '0003_cardmodel_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardModel',
        ),
    ]
